name: MiRanfla

options:
  bundleIdPrefix: com.urielh
  xcodeVersion: 15.4
  deploymentTarget:
    iOS: "17.0"
  useTabs: false
  postGenCommand: "open MiRanfla.xcodeproj"

settings:
  base:
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 5P4JJDT7CR
    MARKETING_VERSION: "1.0.0"
    BUNDLE_VERSION: "1"
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.0

targets:
  MiRanfla:
    settings:
      TARGET_DEVICE_FAMILY: 1
      SUPPORTS_MACCATALYST: false
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
      ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
    platform: iOS
    type: application
    sources:
      - MiRanfla
    scheme:
      testTargets:
        - MiRanflaTests
      gatherCoverageData: true
      coverageTargets:
        - MiRanfla
    info:
      path: MiRanfla/Supporting Files/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        UIAppFonts: [Nunito-Bold.ttf, Nunito-SemiBold.ttf, Nunito-Medium.ttf, Nunito-Regular.ttf]
  MiRanflaTests:
    settings:
      TARGET_DEVICE_FAMILY: 1
      SUPPORTS_MACCATALYST: false
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
    platform: iOS
    type: bundle.unit-test
    dependencies:
      - target: MiRanfla
    sources:
      MiRanflaTests
    info:
      path: MiRanflaTests/Info.plist
